name: Prepare Chat Paste Pack
on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * *"   # 毎日06:00 JST（UTC 21:00）
permissions:
  contents: read
  actions: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Build chat packs
        run: |
          python -m pip install --upgrade pip
          python tools/make_chat_pack.py
      - name: Upload chat packs (both)
        uses: actions/upload-artifact@v4
        with:
          name: chat-paste-pack
          path: |
            chat_build/INDEX.txt
            chat_build/factor_pack/chat-pack.txt
            chat_build/factor_pack/INDEX.txt
            chat_build/factor_pack/chunks/*.txt
            chat_build/drift_pack/chat-pack.txt
            chat_build/drift_pack/INDEX.txt
            chat_build/drift_pack/chunks/*.txt
      - name: Job summary (how to use)
        run: |
          echo "Open the 'chat-paste-pack' artifact and choose 'factor_pack' or 'drift_pack'. Copy 'chat-pack.txt' (or the chunks) into ChatGPT." >> $GITHUB_STEP_SUMMARY
