name: Prepare Chat Paste Pack
on:
  push:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: read
  actions: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build chat-pack.txt (single file)
        run: |
          python -m pip install --upgrade pip
          python tools/make_chat_pack.py

      - name: Upload chat-pack as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chat-paste-pack
          path: chat_build/chat-pack.txt

      - name: Job summary (how to get it)
        run: |
          echo "Artifact **chat-paste-pack** に chat-pack.txt が出力されています。" >> $GITHUB_STEP_SUMMARY
          echo "Actions 実行ページの Artifacts からダウンロードしてください。" >> $GITHUB_STEP_SUMMARY
