name: Prepare Chat Paste Pack
on:
  push:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: write
  actions: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Build chat-pack.txt (single file)
        run: |
          python -m pip install --upgrade pip
          python tools/make_chat_pack.py

      - name: Commit chat-pack.txt back to repo
        run: |
          git config user.name "chat-pack-bot"
          git config user.email "bot@users.noreply.github.com"
          git add chat_build/chat-pack.txt
          git commit -m "chore(chat): update chat-pack.txt" || echo "no changes"
          git push

      - name: Print chat-pack into Job Summary (with truncation)
        run: |
          MAX=$((1024*1024 - 4096))
          echo "### chat-pack.txt (preview)" >> $GITHUB_STEP_SUMMARY
          BYTES=$(wc -c < chat_build/chat-pack.txt)
          if [ $BYTES -le $MAX ]; then
            echo '```text' >> $GITHUB_STEP_SUMMARY
            cat chat_build/chat-pack.txt >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          else
            echo "_Truncated (file > ~1MB). Open the committed file instead._" >> $GITHUB_STEP_SUMMARY
          fi

