name: Prepare Chat Paste Pack

on:
  push:
    branches: [main]
    paths-ignore:
      - 'CodeForChat/**'
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build chat packs into CodeForChat/
        run: |
          python -m pip install --upgrade pip
          python tools/make_chat_pack.py

      - name: Commit generated packs to main
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CodeForChat/
          git diff --cached --quiet || git commit -m "Update Chat Packs [skip ci]"
          git diff --cached --quiet || git push

