name: Prepare Chat Paste Pack
on:
  push:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: write
  actions: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build chat-pack.txt (single file)
        run: |
          python -m pip install --upgrade pip
          python tools/make_chat_pack.py

      - name: Commit chat-pack.txt back to repo
        run: |
          git config user.name "chat-pack-bot"
          git config user.email "bot@users.noreply.github.com"
          git add chat_build/chat-pack.txt
          git commit -m "chore(chat): update chat-pack.txt" || echo "no changes"
          git push

      # \u25bc \u3053\u3053\u304b\u3089\u8ffd\u52a0\uff1a\u30ef\u30f3\u30bf\u30c3\u30d7\u30b3\u30d4\u30fc\u7528\u306e HTML \u3092\u751f\u6210\u3057\u3066\u30b3\u30df\u30c3\u30c8
      - name: Build one-tap copy page (docs/chat-pack.html)
        run: |
          mkdir -p docs
          python - <<PY
          import pathlib
          txt = pathlib.Path('chat_build/chat-pack.txt').read_text(encoding='utf-8')
          esc = txt.replace('\', '\\').replace('`','\`')
          html_page = f"""<!doctype html><meta charset="utf-8"><meta name=viewport content="width=device-width,initial-scale=1">
          <title>Chat Pack – One Tap Copy</title>
          <style>
            body{{font-family:-apple-system,system-ui,Segoe UI,Roboto; margin:16px; line-height:1.5}}
            button{{font-size:18px; padding:12px 16px;}}
            textarea{{width:100%; height:70vh; margin-top:12px; font-family:ui-monospace,Menlo,monospace}}
            .note{{color:#555; font-size:14px}}
          </style>
          <h1>Chat Pack</h1>
          <p class=note>下のボタンで <b>全コピー</b> できます。iPhone/Safari/アプリで動作。コピーできない場合はテキスト欄を長押し→「すべて選択→コピー」。</p>
          <button id="copy">全コピー</button>
          <textarea id="box" readonly></textarea>
          <script>
          const content = `""" + esc + """`;
          const box = document.getElementById('box'); box.value = content;
          document.getElementById('copy').onclick = async () => {
            try {
              await navigator.clipboard.writeText(content);
              alert('コピーしました');
            } catch (e) {
              box.select(); document.execCommand('copy');
              alert('コピーしました（フォールバック）');
            }
          };
          </script>
          """
          pathlib.Path('docs/chat-pack.html').write_text(html_page, encoding='utf-8')
          PY

      - name: Commit one-tap copy page
        run: |
          git config user.name "chat-pack-bot"
          git config user.email "bot@users.noreply.github.com"
          git add docs/chat-pack.html
          git commit -m "feat(chat): add one-tap copy page (docs/chat-pack.html)" || echo "no changes"
          git push

      # Job Summary \u306b\u30d7\u30ec\u30d3\u30e5\u30fc\uff08~1MB\u307e\u3067\uff09
      - name: Print chat-pack into Job Summary (with truncation)
        run: |
          MAX=$((1024*1024 - 4096))
          echo "### chat-pack.txt (preview)" >> $GITHUB_STEP_SUMMARY
          BYTES=$(wc -c < chat_build/chat-pack.txt)
          if [ $BYTES -le $MAX ]; then
            echo '```text' >> $GITHUB_STEP_SUMMARY
            cat chat_build/chat-pack.txt >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          else
            echo "_Truncated (file > ~1MB). Open docs/chat-pack.html to copy._" >> $GITHUB_STEP_SUMMARY
          fi

      # \uff08\u4efb\u610f\uff09Artifacts\u3082\u6b32\u3057\u3051\u308c\u3070\u30b3\u30e1\u30f3\u30c8\u30a2\u30a6\u30c8\89e3\u9664
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: chat-paste-pack
      #     path: chat_build/chat-pack.txt
