name: yf-candidate-health
on:
  workflow_dispatch:
    inputs:
      tickers:
        description: "candidate銘柄（カンマ/改行区切り）。空なら candidate_tickers.csv を使用"
        required: false
        default: ""

jobs:
  run-probe:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas requests
      - name: Check Slack secret
        env: { SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} }
        run: |
          [ -n "${SLACK_WEBHOOK_URL}" ] || (echo "::error ::Missing secret SLACK_WEBHOOK_URL" && exit 78)
      - name: Check candidate CSV
        run: |
          test -s candidate_tickers.csv || (echo "::error ::candidate_tickers.csv not found or empty" && exit 78)
          head -n 20 candidate_tickers.csv || true
      - name: Run probe (manual; candidate.csv)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          CAND_TICKERS: ${{ github.event.inputs.tickers }}
          CAND_FILE: candidate_tickers.csv
          REQUIRE_CAND: "1"
          YF_PROBE_PERIOD: "180d"
          YF_PROBE_MIN_LEN: "120"
          YF_PROBE_MAX_NAN: "0.15"
          YF_PROBE_RETRY: "1"
          YF_PROBE_TIMEOUT_MS_WARN: "5000"
          END_OFFSET_DAYS: "1"
        run: python tools/yf_health_probe.py
