name: yf-health-probe
on:
  push:
    branches:
      - main

jobs:
  run-probe:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas requests
      - run: python yf_health_probe.py
        env:
          YF_PROBE_SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          YF_PROBE_PERIOD: "180d"
          YF_PROBE_MIN_LEN: "120"
          YF_PROBE_MAX_NAN: "0.15"
          YF_PROBE_RETRY: "1"
          YF_PROBE_TIMEOUT_MS_WARN: "5000"
