name: yf-health-probe
on:
  push:
    branches: [ main ]

jobs:
  run-probe:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas requests

      - name: Check secret presence
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [ -z "${SLACK_WEBHOOK_URL}" ]; then
            echo "::error ::Missing repository secret 'SLACK_WEBHOOK_URL'"
            exit 78
          else
            echo "SLACK_WEBHOOK_URL is set (masked)"
          fi

      - name: Run probe
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          YF_PROBE_PERIOD: "180d"
          YF_PROBE_MIN_LEN: "120"
          YF_PROBE_MAX_NAN: "0.15"
          YF_PROBE_RETRY: "1"
          YF_PROBE_TIMEOUT_MS_WARN: "5000"
          YF_PROBE_SOFT_FAIL: "1"
        run: python tools/yf_health_probe.py
